import nlp from "compromise";
const stopWords = new Set([
    "hobbies",
    "entertainment",
    "leisure",
    "movies",
    "cinema",
    "film industry",
    "blockbusters",
    "indie films",
    "movie night",
    "film reviews",
    "actor",
    "director",
    "script",
    "soundtrack",
    "background score",
    "cinematography",
    "special effects",
    "animation",
    "Hollywood",
    "Bollywood",
    "streaming services",
    "OTT platforms",
    "Netflix",
    "Prime Video",
    "Disney+",
    "theater",
    "IMAX",
    "3D movies",
    "comedy movies",
    "horror movies",
    "thriller",
    "sci-fi",
    "documentary",
    "musicals",
    "fantasy movies",
    "romantic movies",
    "action films",
    "film festivals",
    "awards",
    "Oscars",
    "Golden Globe",
    "Cannes",
    "music",
    "songs",
    "playlist",
    "concerts",
    "live music",
    "karaoke",
    "pop music",
    "rock music",
    "jazz",
    "hip-hop",
    "rap",
    "country music",
    "classical music",
    "EDM",
    "instrumentals",
    "music streaming",
    "Spotify",
    "Apple Music",
    "YouTube Music",
    "radio",
    "podcasts",
    "audiobooks",
    "travel",
    "vacation",
    "adventure",
    "road trip",
    "backpacking",
    "beaches",
    "mountains",
    "forests",
    "national parks",
    "wildlife safari",
    "heritage sites",
    "historical places",
    "monuments",
    "tourist attractions",
    "museums",
    "art galleries",
    "cultural heritage",
    "archaeology",
    "ancient ruins",
    "famous landmarks",
    "Taj Mahal",
    "Eiffel Tower",
    "Colosseum",
    "Great Wall of China",
    "Machu Picchu",
    "Pyramids of Giza",
    "Christ the Redeemer",
    "Statue of Liberty",
    "Golden Temple",
    "Qutub Minar",
    "Red Fort",
    "Hawa Mahal",
    "Charminar",
    "Leaning Tower of Pisa",
    "Grand Canyon",
    "Niagara Falls",
    "mountain trekking",
    "hiking trails",
    "camping",
    "stargazing",
    "theme parks",
    "amusement parks",
    "roller coasters",
    "water parks",
    "picnic",
    "cycling",
    "fishing",
    "boating",
    "surfing",
    "scuba diving",
    "skydiving",
    "paragliding",
    "skiing",
    "snowboarding",
    "festivals",
    "music festivals",
    "film festivals",
    "art festivals",
    "food festivals",
    "cooking",
    "baking",
    "restaurant hopping",
    "street food",
    "fine dining",
    "cafes",
    "book reading",
    "libraries",
    "bookstores",
    "novels",
    "fiction",
    "non-fiction",
    "self-improvement",
    "poetry",
    "writing",
    "journaling",
    "blogging",
    "vlogging",
    "photography",
    "videography",
    "painting",
    "sketching",
    "sculpting",
    "DIY projects",
    "handicrafts",
    "board games",
    "chess",
    "card games",
    "puzzles",
    "escape rooms",
    "arcade games",
    "console gaming",
    "PC gaming",
    "VR gaming",
    "sports",
    "cricket",
    "football",
    "basketball",
    "badminton",
    "tennis",
    "golf",
    "swimming",
    "fitness",
    "gym workouts",
    "yoga",
    "meditation",
    "dance",
    "Zumba",
    "martial arts",
    "stand-up comedy",
    "theater plays",
    "poetry slams",
    "storytelling",
    "astronomy",
    "bird watching",
    "gardening",
    "volunteering",
    "social work",
    "charity events",
    "pet care",
    "zoo visits",
    "aquariums",
    "science museums",
    "space exploration",
    "tech exhibitions",
    "cultural events",
    "language learning",
    "foreign cultures",
    "history tours",
    "spiritual retreats",
    "wellness retreats",
    "massage therapy",
    "spa days"
]
);

export default function extractKeywords(sentence) {
    const doc = nlp(sentence);
    const terms = doc.terms().out("array");
    const keywords = terms.filter((word) => !stopWords.has(word.toLowerCase()));
    return keywords;
}